package de.tu_darmstadt;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * Created by Stathis on 6/20/17.
 */
@DatabaseTable(tableName = "sharesToShareHolders")
public class ManyToMany {

    public final static String SHAREHOLDER_ID_FIELD_NAME = "shareholder_id";
    public final static String SHARE_ID_FIELD_NAME = "share_id";

    /**
     * This id is generated by the database and set on the object when it is passed to the create method. An id is
     * needed in case we need to update or delete this object in the future.
     */
    @DatabaseField(generatedId = true)
    int id;

    // This is a foreign object which just stores the id from the User object in this table.
    @DatabaseField(foreign = true, columnName = SHAREHOLDER_ID_FIELD_NAME)
    ShareHolder shareHolder;

    // This is a foreign object which just stores the id from the Post object in this table.
    @DatabaseField(foreign = true, columnName = SHARE_ID_FIELD_NAME)
    Share share;

    ManyToMany() {
        // for ormlite
    }

    public ManyToMany(ShareHolder shareHolder, Share share) {
        this.shareHolder = shareHolder;
        this.share = share;
    }
}