package de.tu_darmstadt;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import java.io.Serializable;


/**
 * Created by Stathis on 6/19/17.
 */
@DatabaseTable(tableName = "shareholders")
public class ShareHolder implements Serializable{

    // we use this field-name so we can query for posts with a certain id
    public final static String ID_FIELD_NAME = "id";

    // this id is generated by the database and set on the object when it is passed to the create method
    @DatabaseField(generatedId = true, columnName = ID_FIELD_NAME)
    int id;
    @DatabaseField
    private String ipAddress;
    @DatabaseField
    private int port;


    public ShareHolder(){}

    public ShareHolder(String ipAddress, int port){
        this.ipAddress = ipAddress;
        this.port = port;

    }

    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public int getPort() {
        return port;
    }

    public void setPort(int port) {
        this.port = port;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }


    public String toString(){
        return "ID: " + id + " IP ADDRESS: " + ipAddress + " PORT: " + port;
    }
}